spring:
  application:
    name: Config-dev
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
#eureka server ka url btayenge 
    service-url:
      defaultZone: http://service-discovery:8761/eureka/
